name: dashed_circle
description: A flutter package for drawing dashed circles. Can also be used with CustomPaint.
version: 0.0.1
author: Niklas Portmann <niklaspor@gmail.com>
homepage: https://gitlab.com/NiklasPor/dashed-circle

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: